name: Reusable CI-CD workflow

on:
  workflow_dispatch:
    inputs:
      application:
        description: 'Name of the application'
        type: choice
        options:
          - application-1
          - application-2
          - application-3

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-lates
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Buld
        run: echo "Building the application"
      
  deploy-test:
    name: Deploy to TEST
    needs: build
    uses: ./github/workflows/deploy-to-environment.yaml@main
    with:
      environment: test
      applicationName: ${{ inputs.application }}
    secrets: inherit

  deploy-staging:
    name: Deploy to STAGING
    needs: deploy-test
    uses: ./github/workflows/deploy-to-environment.yaml@main
    with:
      environment: staging
      applicationName: ${{ inputs.application }}
    secrets: inherit

  deploy-prod:
    name: Deploy to PROD
    needs: deploy-staging
    uses: ./github/workflows/deploy-to-environment.yaml@main
    with:
      environment: prod
      applicationName: ${{ inputs.application }}
    secrets: inherit
