name: Mock deployment action
description: 'Mock deployment action to demonstrate reusable workflows'

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: string
        required: true
      applicationName:
        description: 'Name of the application'
        type: string
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest'

    steps:
      - name: Deploying ${{ inputs.applicationName }} to ${{ inputs.environment }}
        shell: bash
        run: |
          echo "Deploying to ${{ inputs.environment }}"
